### ISSUE TITLE
Poder executar o contedor con usuario non root

### ISSUE THREAD

**Issue by damufo** [dinahosting/dinaip-linux-shell#5]
Boas, 

Grazas polo traballo

No seguinte docker compose

```
name: dinaip
services:
    dinaip:
        environment:
            - DHUSER=${DINAIP_USERNAME}
            - DHPASS=${DINAIP_PASSWORD}
        volumes:
            - ${DINAIP_CONFIG_FOLDER}:/var/persistent
        image: vrdominguez/dinaip:alpine
        user: "${UID}:${GID}"
        container_name: dinaip
        restart: unless-stopped
```

O caso é que non vai porque di que precisa correr como root.
Como podería facer para poder correr o contedor cun usuario non root?
Grazas!!
